name: Tests
on: [push, pull_request]
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
jobs:
  check-sha256-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test
      - run: cargo run --release --example sha256
  check-sha256-example-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: wasm32-unknown-unknown
    - name: Check Build
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target wasm32-unknown-unknown
    - name: Run Tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --target wasm32-unknown-unknown
    - name: Run Example
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release --example sha256 --target wasm32-unknown-unknown

