name: Tests
on: [push, pull_request]
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
jobs:
  check-sha256-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo run --release --example sha256
